"""add_responsible_name_to_clients

Revision ID: 3c8954e65f54
Revises: 42cdf0cc6e8c
Create Date: 2026-03-21 23:01:10.406011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8954e65f54'
down_revision: Union[str, Sequence[str], None] = '42cdf0cc6e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsible_name', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_clients_responsible_name'), ['responsible_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_responsible_name'))
        batch_op.drop_column('responsible_name')

    # ### end Alembic commands ###
