"""Add catalog_items table

Revision ID: 42cdf0cc6e8c
Revises: ca5141d48942
Create Date: 2026-03-21 21:51:37.550252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42cdf0cc6e8c'
down_revision: Union[str, Sequence[str], None] = 'ca5141d48942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_items_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_items_name'))
        batch_op.drop_index(batch_op.f('ix_catalog_items_id'))

    op.drop_table('catalog_items')
    # ### end Alembic commands ###
