"""add_whatsapp_safety_settings

Revision ID: dd896cc8d456
Revises: 3c8954e65f54
Create Date: 2026-07-15 12:30:24.148957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd896cc8d456'
down_revision: Union[str, Sequence[str], None] = '3c8954e65f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_warn_new_number', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('whatsapp_limit_active_chats', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('whatsapp_limit_count', sa.Integer(), nullable=False, server_default=sa.text('10')))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_limit_count')
        batch_op.drop_column('whatsapp_limit_active_chats')
        batch_op.drop_column('whatsapp_warn_new_number')

    # ### end Alembic commands ###
